### ISSUE TITLE
add attribution to all pages which include data originating in RDA Registry

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/webviews#9]
Perhaps do this by updating [CC0-footer.xsl](https://github.com/uwlib-cams/webviews/blob/master/xsl/CC0-footer.xsl) to include optional attribution content.
See also https://github.com/uwlib-cams/map_storage/issues/42.

**Comment by cspayne** [comment]
attribution footers added to all legacy html pages, and relevant css and xsl stylesheets.

**Comment by cspayne** [comment]
note: current html templates for rts have also been updated using 004_01_storage_to_html.xsl

**Comment by briesenberg07** [comment]
Thank you @cspayne !
